#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dagu"
name = "Dagu"
description.en = "Cron alternative that comes with a Web UI"
description.fr = "Alternative à Cron fournie avec une interface utilisateur Web"

version = "2.3.8~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
admindoc = "https://docs.daguit.dev/"
code = "https://github.com/dagu-org/dagu"
website = "https://dagu.cloud/"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/dagu-org/dagu/releases/download/v2.3.8/dagu_2.3.8_linux_amd64.tar.gz"
    amd64.sha256 = "df4a64d6c9942db7d23e1b7121d87ed2c10d4e64ec9c509a0760882229620bd2"
    arm64.url = "https://github.com/dagu-org/dagu/releases/download/v2.3.8/dagu_2.3.8_linux_arm64.tar.gz"
    arm64.sha256 = "e00f47b8928b82ad776e7e06ecd660bca18c407fe59b7beec8cc159e44f9ba7a"
    armhf.url = "https://github.com/dagu-org/dagu/releases/download/v2.3.8/dagu_2.3.8_linux_armv7.tar.gz"
    armhf.sha256 = "73d4cc98f0e7a9428a0383d29077ac4bc46421122fbabdd2abf93aef2c6751b6"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^dagu_.*_linux_amd64.tar.gz$"
    autoupdate.asset.armhf = "^dagu_.*_linux_armv7.tar.gz$"
    autoupdate.asset.arm64 = "^dagu_.*_linux_arm64.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
