#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dagu"
name = "Dagu"
description.en = "Cron alternative that comes with a Web UI"
description.fr = "Alternative à Cron fournie avec une interface utilisateur Web"

version = "2.3.11~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
admindoc = "https://docs.daguit.dev/"
code = "https://github.com/dagu-org/dagu"
website = "https://dagu.cloud/"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/dagu-org/dagu/releases/download/v2.3.11/dagu_2.3.11_linux_amd64.tar.gz"
    amd64.sha256 = "68d1bf353dea71f3caf0377e0dbc75df0fa7c89cd2b9f8a0b6e043afc7ba9cbb"
    arm64.url = "https://github.com/dagu-org/dagu/releases/download/v2.3.11/dagu_2.3.11_linux_arm64.tar.gz"
    arm64.sha256 = "d314b0c11ff247a2c90a4145f6510be922b34455d63eefceaa64fc2bf7b76c63"
    armhf.url = "https://github.com/dagu-org/dagu/releases/download/v2.3.11/dagu_2.3.11_linux_armv7.tar.gz"
    armhf.sha256 = "e4addfa247947e0303e1e545b2dda255071f1b08cd51bc39b0b46690e80ce693"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^dagu_.*_linux_amd64.tar.gz$"
    autoupdate.asset.armhf = "^dagu_.*_linux_armv7.tar.gz$"
    autoupdate.asset.arm64 = "^dagu_.*_linux_arm64.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
