#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dagu"
name = "Dagu"
description.en = "Cron alternative that comes with a Web UI"
description.fr = "Alternative à Cron fournie avec une interface utilisateur Web"

version = "2.0.3~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
admindoc = "https://docs.daguit.dev/"
code = "https://github.com/dagu-org/dagu"
website = "https://dagu.cloud/"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/dagu-org/dagu/releases/download/v2.0.3/dagu_2.0.3_linux_amd64.tar.gz"
    amd64.sha256 = "c3a248e8300be628be776db1537e487002a881523618b8de7e94a8e6d08e4719"
    arm64.url = "https://github.com/dagu-org/dagu/releases/download/v2.0.3/dagu_2.0.3_linux_arm64.tar.gz"
    arm64.sha256 = "234d7ee2c1e2d3eecc7d66f42ce96b4566d6c968d4fd4d736c7b0a911b50df08"
    armhf.url = "https://github.com/dagu-org/dagu/releases/download/v2.0.3/dagu_2.0.3_linux_armv7.tar.gz"
    armhf.sha256 = "4ab37eefbaaab9ac79c2614c482558577bbd891c6ec7f3d6fb5f0ee8670066f4"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^dagu_.*_linux_amd64.tar.gz$"
    autoupdate.asset.armhf = "^dagu_.*_linux_armv7.tar.gz$"
    autoupdate.asset.arm64 = "^dagu_.*_linux_arm64.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
