# Server settings
host: 127.0.0.1  # Listen on all interfaces
port: __PORT__

# Authentication
auth:
  basic:
    enabled: true
    username: __ADMIN__
    password: ${DAGU_ADMIN_PASSWORD}  # From environment


# Directories
#dagsDir: /opt/dagu/workflows
#logDir: /var/log/__APP__
#dataDir: /var/lib/dagu


# to show latest status of dags from today or history
latestStatusToday: true

# path to the DAGs directory
dags: <the location of DAG configuration files>              # default: ${HOME}/.config/dagu/dags


# API Token
#isAuthToken: <true|false>                                    # enables API token
#authToken: <token for API access>                            # API token

# Base Config
baseConfig: __INSTALL_DIR__/.config/dagu/config.yaml           # default: ${HOME}/.config/dagu/base.yaml

# Working Directory
workDir: ${HOME}/.config/dagu/base.yaml                      # default: DAG location

# SSL Configuration
#tls:
#    certFile: <path to SSL certificate file>
#    keyFile: <path to SSL key file>

schedule: "5 4 * * *" # Run at 04:05.
steps:
  - name: scheduled job
    command: job.sh

# Email notification settings
mailOn:
  failure: true
  success: true

# SMTP server settings
smtp:
  host: "localhost"
  port: "25"
  username: "__APP__"
  password: "__MAIL_PWD__"

# Error mail configuration
errorMail:
  from: "dagu@__DOMAIN__"
  to: "__EMAIL__"
  prefix: "[Error]"

# Info mail configuration
infoMail:
  from: "dagu@__DOMAIN__"
  to: "__EMAIL__"
  prefix: "[Info]"
